### ISSUE TITLE
Api token expiresIn expect milliseconds instead of secconds

### ISSUE THREAD

**Issue by Kuzzy** [adonisjs/auth#202]
## Package version

8.2.1

[Docs says](https://docs.adonisjs.com/guides/auth/api-tokens-guard#expiresin) that `expiresIn` property should be in seconds:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/1777393/179073373-042df2a0-781c-40a6-850f-bc6f245f4975.png">

But in real it awaits for milliseconds: https://github.com/adonisjs/auth/blob/946e730cdebcfd277cf69ce29d5be40c80a25ce0/src/Guards/Oat/index.ts#L125

I'm not sure where better to address this issue here or in repo with docs, but in my opinion it would be more user friendly to use seconds. For example, [Redis setex](https://redis.io/commands/setex/), which is used under the hood  (if storage is Redis), is using a seconds.

**Comment by thetutlage** [comment]
Alright, checked the codebase and docs both.

The docs you have shared links to the return value of `auth.generate` and not the config accepted. So basically, you are looking at the config property `expiresIn` and confusing it with the return value of `auth.generate` method

**Comment by thetutlage** [comment]
Feel free to reopen the issue if you have any questions

**Comment by mcordoba** [comment]
The docs are wrong for both ways of specify the value of expiresIn.

For numbers, it says seconds instead of milliseconds but...

for string it uses this format as an example: '7days' or '30mins' and is wrong according to ms package:

https://www.npmjs.com/package/ms

The right way of specify is including a white space '7 days' or '30 mins'

I have tested both cases. Please update the docs.

**Comment by mcordoba** [comment]
@thetutlage sorry added link! but im pretty sure you knew where to find it :P
